name: Generate Contributors Image

on:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
  push:
    branches:
      - master

jobs:
  contributors:
    runs-on: ubuntu-latest
    if: github.repository == 'wailsapp/wails'
    steps:
      - uses: actions/checkout@v3
      - uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          avatarSize: 100  # Set the avatar size.
          
      - name: Modify htmlTable credits.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          openDelimiter: ' <!--GAMFC_DELIMITER-->'
          closeDelimiter: '<!--GAMFC_DELIMITER-END-->'
          path: website/src/pages/credits.mdx
          body: '${{steps.contributors.outputs.htmlTable}}'
          ref: chore/update-contributors
